### ISSUE TITLE
BUG: Evaluate Facility address causing issues

### ISSUE THREAD

**Issue by lina-roth** [CDCgov/phdi#2698]
Looks like there is an issue I’m seeing with facility address information -
Ecr - daf7f4ae-bff3-11ec-81e1-8465ad080d41

Error:
```
error.tsx:18 TypeError: Cannot read properties of undefined (reading '0')
    at evaluateFacilityData (evaluateFhirDataService.ts:406:71)
    at AccordionContent (AccordionContent.tsx:50:44)
```

**Comment by lina-roth** [comment]
this was already fixed in main, I was just working on a non updated branch
