### ISSUE TITLE
Demo UI shows error when zip file can't be unzipped

### ISSUE THREAD

**Issue by emmastephenson** [CDCgov/phdi#878]
## Action Requested
If a zip file without eICR/RR is uploaded, it is rejected by the orchestration API and the frontend shows the appropriate error to the user.

## Acceptance Criteria
If a non-eCR zip is uploaded, it is rejected and the frontend errors out according to [this design](https://www.figma.com/file/YU5hAHY1Eg7J6gtNbBxm7d/DIBBs-Demo-Site?type=design&node-id=212-1997&mode=design&t=QJqOS9RF0ULUPXSa-0).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzViQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ea1de730bcd11c5e8faacf61679e5bb0806b5f5/Screenshot%202023-10-20%20at%2012.13.00%20PM.png)

## Testing
Unit testing, both FE & BE

## Background & Context
Users need to understand exactly why their file has failed to process.

**Comment by robertandremitchell** [comment]
Currently, if you upload any random zip file, it just "hangs" on the page without any error message. On the backend, it does not actually provide that helpful of an error message, either. It mostly is just noting 
```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 247, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/fastapi/applications.py", line 276, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/starlette/routing.py", line 82, in app
    await func(session)
  File "/Users/rob/phdi/containers/orchestration/.venv/lib/python3.10/site-packages/fastapi/routing.py", line 289, in app
    await dependant.call(**values)
  File "/Users/rob/phdi/containers/orchestration/app/main.py", line 81, in process_message_endpoint_ws
    unzipped_file = unzip_ws(zipped_file)
  File "/Users/rob/phdi/containers/orchestration/app/utils.py", line 46, in unzip_ws
    file_to_open = [
IndexError: list index out of range
INFO:     connection closed
```
https://github.com/CDCgov/phdi/blob/main/containers/orchestration/app/utils.py#L43 is the function that does this and gets called here: https://github.com/CDCgov/phdi/blob/main/containers/orchestration/app/main.py#L81.

The lightest lift to prevent the function from erroring is to build out the utils.py function with empty criteria in mind. If len of the EICR's is 0, then we would flag there.

**Comment by robertandremitchell** [comment]
I'm admittedly fairly ignorant on front-end things, but I think this is where we would add logic that if the data dictionary is null that we could add a message indicating that the zip does not contain the required data: https://github.com/CDCgov/phdi-playground/blob/main/front-end/app/upload_file/page.tsx#L51
